Pagination
SuperCATDevelopers/SuperCAT pull request #73
Opened 2022-02-04 15:48 UTC by FredericIV

Major:
- Add paging support
- Fix HDD name pull
- Fix error in time setting
Minor:
- Change "Drive Name" to "Drive Number"

2022-02-07 14:29 UTC, stevenevans1197 approved these changes

2022-02-07 14:41 UTC, lordneeko requested changes
Github is complaining of merge conflicts. Check those out and resolve prior to pushing.

2022-02-09 12:49 UTC, FredericIV commented
Conflict resolved

2022-02-15 14:06 UTC, lordneeko approved these changes

2022-02-15 14:06 UTC, merged